# This is a basic workflow to help you get started with Actions

name: test

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'specifiy which environment to run the tests on. Available values: dev, qa, staging, prod'     
        required: true
        default: 'dev'
      gitRef:
        description: 'specify which git branch, tag or SHA reference of the tests to run'
        required: true
        default: master

jobs:
  runQAtests:
    runs-on: ubuntu-latest
    if: ${{ github.actor == "aiden.petersen1" }}
    steps:
    - run: |
        echo "Environment: ${{ github.event.inputs.environment }}, gitRef: ${{ github.event.inputs.gitRef }}, user: ${{ github.actor }} , ref: ${{ github.ref }}"
