# This is a basic workflow to help you get started with Actions

name: test

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'specifiy which environment to run the tests on. Available values: dev, qa, staging, prod'     
        required: true
        default: 'dev'

jobs:
  runQAtests:
    runs-on: ubuntu-latest
    env:
      ENV: "DEV"
      DEV_PLATFORM: "working"
    steps:
     - name: beep
       run: |
        echo "::set-env name=PLATFORM_BASE_RUL::eval echo \$${ENV}_PLATFORM"
     - name: print var
       run: echo $PLATFORM_BASE_URL
